=== PegaPii/cv24v1/src/main/resources/xml/cv24.tp1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://univ.fr/cv24" xmlns="http://univ.fr/cv24" 
		   elementFormDefault="qualified" >

<xs:element name="cv24" type="cv24Type"/>

<xs:complexType name="cv24Type">
	<xs:sequence>
		<xs:element name="identite" type="identiteType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="objectif" type="objectifType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="prof" type="profType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="competences" type="competencesType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="divers" type="diversType" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="genreType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="M."/>
		<xs:enumeration value="Mme"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="nomType">
	<xs:restriction base="xs:string">
		<xs:maxLength value="32"/>
		<xs:pattern value="[A-Z]+"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="prenomType">
	<xs:restriction base="xs:string">
		<xs:maxLength value="32"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="telType">
	<xs:restriction base="xs:string">
		<xs:pattern value="0[1-9]([0-9] ?){8}"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="melType">
	<xs:restriction base="xs:string">
		<xs:pattern value="[a-zA-Z0-9._]+@[a-zA-Z.-]+\.[a-zA-Z]{2,}"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="identiteType">
	<xs:sequence>
		<xs:element name="genre" type="genreType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="nom" type="nomType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="prenom" type="prenomType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="tel" type="telType" minOccurs="0" maxOccurs="1"/>
		<xs:element name="mel" type="melType" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="statutType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="stage"/>
		<xs:enumeration value="emploi"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="objectifType">
	<xs:simpleContent>
		<xs:extension base="objSizeType">
			<xs:attribute name="statut" type="statutType" use="required"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:simpleType name="objSizeType">
	<xs:restriction base="xs:string">
		<xs:maxLength value="128"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="profType">
	<xs:sequence>
		<xs:element name="detail" type="detailType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="detailType">
	<xs:sequence>
		<xs:element name="titre" type="titreType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="datedeb" type="xs:date" minOccurs="1" maxOccurs="1"/>
		<xs:element name="datefin" type="xs:date" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="titreType">
	<xs:restriction base="xs:string">
		<xs:maxLength value="128"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="competencesType">
	<xs:sequence>
		<xs:element name="diplome" type="diplomeType" minOccurs="1" maxOccurs="5"/>
		<xs:element name="certif" type="certifType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="string32Type">
	<xs:restriction base="xs:string">
		<xs:maxLength value="32"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="diplomeType">
	<xs:sequence>
		<xs:element name="titre" type="titreType" minOccurs="1" maxOccurs="5"></xs:element>
		<xs:element name="date" type="xs:date" minOccurs="1" maxOccurs="1"/>
		<xs:element name="institut" type="string32Type" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="niveau" type="niveauType" use="required"/>
</xs:complexType>

<xs:simpleType name="niveauType">
	<xs:restriction base="xs:int">
		<xs:enumeration value="3"/>
		<xs:enumeration value="4"/>
		<xs:enumeration value="5"/>
		<xs:enumeration value="6"/>
		<xs:enumeration value="7"/>
		<xs:enumeration value="8"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="qualifType">
	<xs:restriction base="xs:string">
		<xs:maxLength value="32"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="certifType">
	<xs:sequence>
		<xs:element name="datedeb" type="xs:date" minOccurs="1" maxOccurs="1"/>
		<xs:element name="datefin" type="xs:date" minOccurs="0" maxOccurs="1"/>
		<xs:element name="titre" type="string32Type" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="diversType">
	<xs:sequence>
		<xs:element name="lv" type="lvType" minOccurs="1" maxOccurs="5"/>
		<xs:element name="autre" type="autreType" minOccurs="0" maxOccurs="3"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="lvType">
	<xs:attribute name="lang" type="langType" use="required"/>
	<xs:attribute name="cert" type="certType" use="required"/>
	<xs:attribute name="nivs" type="nivsType" use="optional"/>
	<xs:attribute name="nivi" type="niviType" use="optional"/>
</xs:complexType>

<xs:simpleType name="langType">
	<xs:restriction base="xs:string">
		<xs:pattern value="[a-z]{2}"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="certType">
	<xs:annotation>
		<xs:appinfo>
            <requirements>
              <requirement certType="CLES" nivsType="true"/>
              <requirement certType="TOEIC" niviType="true"/>
            </requirements>
		</xs:appinfo>
	</xs:annotation>
	<xs:restriction base="xs:string">
		<xs:enumeration value="MAT"/>
		<xs:enumeration value="CLES"/>
		<xs:enumeration value="TOEIC"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="nivsType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="A1"/>
		<xs:enumeration value="A2"/>
		<xs:enumeration value="B1"/>
		<xs:enumeration value="B2"/>
		<xs:enumeration value="C1"/>
		<xs:enumeration value="C2"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="niviType">
	<xs:restriction base="xs:int">
		<xs:minInclusive value="10"/>
		<xs:maxInclusive value="990"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="autreType">
	<xs:attribute name="titre" type="string32Type" use="required"/>
	<xs:attribute name="comment" type="titreType" use="optional"/>
</xs:complexType>

</xs:schema>

=== PegaPii/cv24v1/src/main/resources/tp_resources/cv24.tp21.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd ">
  <identite>
    <genre>M.</genre>
    <nom>NOM</nom>
    <prenom>prenom</prenom>
    <tel>0765432100</tel>
  </identite>
  <objectif statut="stage">objectif</objectif>
  <prof>
    <detail>
      <datedeb>2001-01-01</datedeb>
      <titre>titre</titre>
    </detail>
  </prof>
  <competences>
    <diplome niveau="3">
      <date>2001-01-01</date>
    </diplome>
    <certif>
      <datedeb>2001-01-01</datedeb>
      <titre>titre</titre>
    </certif>
  </competences>
  <divers>
    <lv cert="MAT" lang="it"/>
    <autre comment="" titre="">autre</autre>
  </divers>
</cv24:cv24>

=== PegaPii/cv24v1/src/main/resources/xml/tp1.good2.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 ../tp_resources/cv24.tp1.xsd ">
  <cv24:identite>
    <cv24:genre>Mme</cv24:genre>
    <cv24:nom>THIBERVILLE</cv24:nom>
    <cv24:prenom>Malvina</cv24:prenom>
    <cv24:tel>0212345678</cv24:tel>
    <cv24:mel>nomprenom@gmail.com</cv24:mel>
  </cv24:identite>
  <cv24:objectif statut="stage">Stage</cv24:objectif>
  <cv24:prof>
    <cv24:detail>
      <cv24:titre>Développement web</cv24:titre>
      <cv24:datedeb>2021-01-19</cv24:datedeb>
    </cv24:detail>
    <cv24:detail>
      <cv24:titre>Développement .NET</cv24:titre>
      <cv24:datedeb>2022-06-29</cv24:datedeb>
      <cv24:datefin>2022-12-29</cv24:datefin>
    </cv24:detail>
  </cv24:prof>
  <cv24:competences>
    <cv24:diplome niveau="4">
      <cv24:titre>Bac</cv24:titre>
      <cv24:date>2019-07-20</cv24:date>
      <cv24:institut>LAY</cv24:institut>
    </cv24:diplome>
    <cv24:diplome niveau="6">
      <cv24:titre>Licence info</cv24:titre>
      <cv24:date>2023-06-15</cv24:date>
      <cv24:institut>Université Rouen Normandie</cv24:institut>
    </cv24:diplome>
    <cv24:certif>
      <cv24:datedeb>2015-04-09</cv24:datedeb>
      <cv24:titre>Scrum Master</cv24:titre>
    </cv24:certif>
    <cv24:certif>
      <cv24:datedeb>2018-03-22</cv24:datedeb>
      <cv24:datefin>2019-03-22</cv24:datefin>
      <cv24:titre>PSC1</cv24:titre>
    </cv24:certif>
  </cv24:competences>
  <cv24:divers>
    <cv24:lv cert="MAT" lang="fr"/>
    <cv24:lv cert="CLES" nivs="B1" lang="en"/>
    <cv24:lv cert="TOEIC" nivi="620" lang="en"/>
    <cv24:autre comment="B" titre="Permis de conduire"/>
  </cv24:divers>
</cv24:cv24>

=== PegaPii/cv24v1/src/main/resources/tp_resources/tp1.02.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:competences xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd ">
  <diplome niveau="0">
    <date>2001-01-01</date>
    <institut>institut</institut>
  </diplome>
  <certif>
    <datedeb>2001-01-01</datedeb>
    <datefin>2001-01-01</datefin>
    <titre>titre</titre>
  </certif>
</cv24:competences>

=== PegaPii/cv24v1/src/main/resources/tp_resources/tp1.bad1.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd ">
  <identite>
    <genre>M.</genre>
    <genre>Mme</genre>
    <prenom>prenom</prenom>
    <nom>nom</nom>
    <tel>tel</tel>
    <mel>mauvaismel.com</mel>
  </identite>
  <objectif statut="stage">objectif</objectif>
  <prof>
    <detail>
      <datedeb>2001-01-01</datedeb>
      <titre>titre</titre>
    </detail>
  </prof>
  <competences>
  	<certif>
      <titre>titre</titre>
      <datedeb>2001-01-01</datedeb>
    </certif>
    <diplome niveau="3">
      <date>date</date>
    </diplome>
  </competences>
  <divers>
    <lv cert="CLES" lang="eng" nivs="B2"/>
    <autre comment="" titre="">autre</autre>
  </divers>
</cv24:cv24>

=== PegaPii/cv24v1/src/main/resources/xml/example_complexe.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd ">
    <cv24:identite>
        <cv24:genre>M.</cv24:genre>
        <cv24:nom>SAPIN</cv24:nom>
        <cv24:prenom>Robin</cv24:prenom>
        <cv24:tel>0605589874</cv24:tel>
        <cv24:mel>robinsapin@gmail.com</cv24:mel>
    </cv24:identite>
    <cv24:objectif statut="emploi">Développeur Java</cv24:objectif>
    <cv24:prof>
        <cv24:detail>
            <cv24:titre>Testeur</cv24:titre>
            <cv24:datedeb>2022-06-19</cv24:datedeb>
            <cv24:datefin>2023-05-04</cv24:datefin>
        </cv24:detail>
        <cv24:detail>
            <cv24:titre>Développeur Full Stack</cv24:titre>
            <cv24:datedeb>2023-07-01</cv24:datedeb>
            <cv24:datefin>2023-12-11</cv24:datefin>
        </cv24:detail>
    </cv24:prof>
    <cv24:competences>
        <cv24:diplome niveau="4">
            <cv24:titre>Bac</cv24:titre>
            <cv24:titre>Scientifique</cv24:titre>
            <cv24:titre>Spécialité SVT</cv24:titre>
            <cv24:date>2017-07-20</cv24:date>
            <cv24:institut>Lycée</cv24:institut>
        </cv24:diplome>
        <cv24:diplome niveau="6">
            <cv24:titre>DUT</cv24:titre>
            <cv24:date>2022-06-15</cv24:date>
            <cv24:institut>Université Rouen Normandie</cv24:institut>
        </cv24:diplome>
        <cv24:certif>
            <cv24:datedeb>2019-08-09</cv24:datedeb>
            <cv24:titre>Toic</cv24:titre>
        </cv24:certif>
        <cv24:certif>
            <cv24:datedeb>2018-03-22</cv24:datedeb>
            <cv24:datefin>2019-03-22</cv24:datefin>
            <cv24:titre>PSC2</cv24:titre>
        </cv24:certif>
    </cv24:competences>
    <cv24:divers>
        <cv24:lv cert="MAT" lang="fr"/>
        <cv24:lv cert="CLES" nivs="B1" lang="en"/>
        <cv24:lv cert="TOEIC" nivi="200" lang="en"/>
        <cv24:autre comment="B" titre="Permis de conduire"/>
        <cv24:autre comment="Mention bien" titre="Brevet de Secourisme"/>
    </cv24:divers>
</cv24:cv24>

=== PegaPii/cv24v1/src/main/resources/tp_resources/cv24.tp22.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd ">
  <cv24:identite>
    <cv24:genre>M.</cv24:genre>
    <cv24:nom>cv24:nom</cv24:nom>
    <cv24:prenom>cv24:prenom</cv24:prenom>
    <cv24:tel>cv24:tel</cv24:tel>
  </cv24:identite>
  <cv24:objectif statut="stage">cv24:objectif</cv24:objectif>
  <cv24:prof>
    <cv24:detail>
      <cv24:datedeb>2001-01-01</cv24:datedeb>
      <cv24:titre>cv24:titre</cv24:titre>
    </cv24:detail>
  </cv24:prof>
  <cv24:competences>
    <cv24:diplome niveau="3">
      <cv24:date>2001-01-01</cv24:date>
    </cv24:diplome>
    <cv24:certif>
      <cv24:datedeb>2001-01-01</cv24:datedeb>
      <cv24:titre>cv24:titre</cv24:titre>
    </cv24:certif>
  </cv24:competences>
  <cv24:divers>
    <cv24:lv cert="MAT" lang="" nivi="0" nivs="A1"/>
    <cv24:autre comment="" titre="">cv24:autre</cv24:autre>
  </cv24:divers>
</cv24:cv24>

=== PegaPii/cv24v1/src/main/resources/xml/exemple_simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd ">
  <cv24:identite>
    <cv24:genre>Mme</cv24:genre>
    <cv24:nom>THIBERVILLE</cv24:nom>
    <cv24:prenom>Malvina</cv24:prenom>
  </cv24:identite>
  <cv24:objectif statut="stage">Stage</cv24:objectif>
  <cv24:competences>
    <cv24:diplome niveau="4">
      <cv24:titre>Bac</cv24:titre>
      <cv24:date>2019-07-20</cv24:date>
    </cv24:diplome>
    <cv24:diplome niveau="6">
      <cv24:titre>Licence info</cv24:titre>
      <cv24:date>2023-06-15</cv24:date>
    </cv24:diplome>
  </cv24:competences>
</cv24:cv24>
